### ISSUE TITLE
Crash du décodeur de PDF

### ISSUE THREAD

**Issue by MrAlex1598** [MrAlex1598/Polytech#1]
Pas d'exception juste un crash ...
Semble arriver quand on charge un nouveau PDF alors qu'un autre est déja affiché

LOG:

03-06 11:04:38.154 24986-24986/fr.univ_tours.polytech A/libc: /home/stefan/lib/vudroid-read-only/jni/mupdf/mupdf/fitz/stm_filter.c:21: fz_process: assertion "in->rp <= in->wp" failed
03-06 11:04:38.154 24986-25307/fr.univ_tours.polytech A/libc: /home/stefan/lib/vudroid-read-only/jni/mupdf/mupdf/fitz/stm_filter.c:21: fz_process: assertion "in->rp <= in->wp" failed
03-06 11:04:38.154 24986-25307/fr.univ_tours.polytech A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 25307 (AsyncTask #5)
03-06 11:04:38.154 24986-24986/fr.univ_tours.polytech A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24986 (_tours.polytech)

**Comment by MrAlex1598** [comment]
I caught one

03-06 11:14:03.494 26587-26640/fr.univ_tours.polytech D/PdfDroid: Exception 'java/lang/RuntimeException', Message: 'error loading page'
03-06 11:14:03.494 26587-26640/fr.univ_tours.polytech D/PdfDroid: PdfPage.nativeOpenPage(): return handle = 0xa39e6270
03-06 11:14:03.495 26587-26640/fr.univ_tours.polytech E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                        Process: fr.univ_tours.polytech, PID: 26587
                                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.RuntimeException: error loading page
                                                                            at org.vudroid.pdfdroid.codec.PdfPage.open(Native Method)
                                                                            at org.vudroid.pdfdroid.codec.PdfPage.createPage(PdfPage.java:55)
                                                                            at org.vudroid.pdfdroid.codec.PdfDocument.getPage(PdfDocument.java:18)
                                                                            at org.vudroid.core.DecodeServiceBase.getPage(DecodeServiceBase.java:175)
                                                                            at com.joanzapata.pdfview.RenderingAsyncTask.proceed(RenderingAsyncTask.java:100)
                                                                            at com.joanzapata.pdfview.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:63)
                                                                            at com.joanzapata.pdfview.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:33)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by MrAlex1598** [comment]
Seems to be caused by the library not decoding properly the pdf, can't do anything for now

**Comment by MrAlex1598** [comment]
Could use finally with a boolean hasCrashed to check if app is dead and relaunch it, might work.
Will try to implement for build 4.
